excluded:
  - JIP4iD/AppDelegate.swift
  - JIP4iD/SceneDelegate.swift
  - JIP4iD/ContentView.swift
  - JIP4iD/swiftlint.txt
  - JIP4iD/.#.swiftlint.yml
  - JIP4iD/#.swiftlint.yml#

identifier_name:
  min_length:
    warning: 3 # use 1 for single character loop counter detection
    error: 0 # use 0 to suppress error
  max_length: 
    warning: 40 # minimum for warning free
    error: 100
  excluded: # examples of excluded variables
    - id
  allowed_symbols: "_" # skipping gives always error
  validates_start_with_lowercase: false # true gives always error

type_name:
  min_length:
    warning: 3 
    error: 0 # less than value gives error
  max_length: # warning and error
    warning: 45 # mimimum for warning free
    error: 100
  excluded: 
# iPhone # excluded via string
  allowed_symbols: "_" # skipping gives always error, is also related to max_length warning
  validates_start_with_lowercase: false # (bug in swiftlint, should be uppercase) true gives always error

dynamic_inline: warning # overrule error
empty_count: warning # overrule error
force_cast: warning # overrule error
force_try: warning # overrule error
#identifier_name_violation: warning # overrule error
no_extension_access_modifier: warning # overrule error
shorthand_operator: warning # overrule error

attributes: # https://github.com/ustwo/brunel/blob/master/.swiftlint.yml
  always_on_same_line:
    - '@IBAction'
    - '@NSManaged'
#    - '@nonobjc'
#    - '@objc'
  always_on_line_above:
# closure_body_length:  # not working
#   warning: 10
#   error: 21
cyclomatic_complexity: # https://medium.com/developerinsider/how-to-use-swiftlint-with-xcode-to-enforce-swift-style-and-conventions-368e49e910
  warning: 10
  error: 21
file_length: # https://medium.com/developerinsider/how-to-use-swiftlint-with-xcode-to-enforce-swift-style-and-conventions-368e49e910
  warning: 300
  error: 773
  ignore_comment_only_lines: true
#function_parameter_count: # not working
#  warning: 5
#  error: 8
line_length: # https://medium.com/developerinsider/how-to-use-swiftlint-with-xcode-to-enforce-swift-style-and-conventions-368e49e910
  warning: 200
  error: 322
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
type_body_length: # https://medium.com/developerinsider/how-to-use-swiftlint-with-xcode-to-enforce-swift-style-and-conventions-368e49e910
  warning: 200
  error: 476

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation # no example seen
  - closure_parameter_position # no example seen
  - closure_spacing
  - collection_alignment # not working
  - conditional_returns_on_newline
#  - contains_over_first_not_nil # not working
#  - convenience_type # not working
#  - discouraged_object_literal # not working
#  - discouraged_optional_boolean # not working
#  - discouraged_optional_collectiona # not working
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
#  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - yoda_condition

file_header:
  forbidden_pattern: |
                     \/\/
                     \/\/  .*?\.swift
                     \/\/  .*?
                     \/\/
                     \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{4}\.
                     \/\/  Copyright © \d{4} Erik Waterham\. All rights reserved\.
                     \/\/
custom_rules:
  empty_first_line: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Empty First Line"
    regex: '(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)'
    message: "There should be an empty line after a declaration"
    severity: warning
  comments_capitalized_find_possible_code: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Catch Commented Out Code"
    regex: '(^ *// +(?!swiftlint)[a-z]+)'
    message: "The first word of a comment should be capitalized"
    severity: warning
  comments_capitalized_ignore_possible_code: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Capitalize First Word In Comment"
    regex: '(^ +// +(?!swiftlint)[a-z]+)'
    message: "The first word of a comment should be capitalized"
    severity: warning
  comments_empty_line_after: # https://github.com/ustwo/brunel/blob/master/.swiftlint.yml
    name: "Comments"
    regex: '([^\n]\n^ *[a-zA-Z0-9{])'
    match_kinds:
      - comment
    message: "There should be an empty line after a comment."
    severity: warning
  comments_space: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Space After Comment"
    regex: '(^ *\/\/\w+)'
    message: "There should be a space after //"
    severity: warning
  double_space: # From https://github.com/IBM-Swift/Package-Builder
    include: "*.swift"
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning
  empty_line_after_guard: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Empty Line After Guard"
    regex: '(^ *guard[ a-zA-Z0-9=?.\(\),><!]*\{[ a-zA-Z0-9=?.\(\),><!]*\}\n *(?!(?:return|guard))\S+)'
    message: "There should be an empty line after a guard"
    severity: warning
  empty_line_after_super: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Empty Line After Super"
    regex: '(^ *super\.[ a-zA-Z0-9=?.\(\)\{\}:,><!]*\n *(?!(?:\}|return))\S+)'
    message: "There should be an empty line after super"
    severity: warning
  explicit_failure_calls: # https://github.com/krzysztofzablocki/Traits/blob/master/Example/.swiftlint.yml
    name: "Avoid asserting 'false'"
    regex: '((assert|precondition)\(false)'
    message: "Use assertionFailure() or preconditionFailure() instead."
    severity: warning
  force_https: # From https://github.com/Twigz/Game
    name: "Force HTTPS over HTTP"
    regex: '((?i)http(?!s))'
    match_kinds: string
    message: "HTTPS should be favored over HTTP"
    severity: warning
  marks_empty_space: # https://github.com/ustwo/brunel/blob/master/.swiftlint.yml
    name: "Marks"
    regex: "(//MARK)"
    message: "There should be an empty space between // and the MARK."
    severity: warning
  marks_style: # https://github.com/ustwo/brunel/blob/master/.swiftlint.yml
    name: "Marks"
    regex: "(// MARK: -?[a-zA-Z0-9])"
    message: "Marks should follow the following structure: // MARK: - Comment."
    severity: warning
  multiple_empty_lines: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Multiple Empty Lines"
    regex: '((?:\s*\n){3,})'
    message: "There are too many line breaks"
    severity: warning
  unnecessary_type: # https://github.com/brandenr/swiftlintconfig/blob/master/.swiftlint.yml
    name: "Unnecessary Type"
    regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[\? ]*= \1'
    message: "Type Definition Not Needed"
    severity: warning

